# Generated by Django 3.2.5 on 2021-07-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plus", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landingpagesurvey",
            name="email",
        ),
        migrations.RemoveField(
            model_name="landingpagesurvey",
            name="user",
        ),
        migrations.RemoveField(
            model_name="landingpagesurvey",
            name="variant",
        ),
    ]
