---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: MySQL server for RHEL/CentOS and Debian/Ubuntu.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 1.9
  platforms:
    - name: EL
      versions:
      - 6
      - 7
    - name: Ubuntu
      versions:
      - all
    - name: Debian
      versions:
      - all
  galaxy_tags:
    - database
