# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-08 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_remove_document_zone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': (('view_document', 'Can view document'), ('move_tree', 'Can move a tree of documents'), ('purge_document', 'Can permanently delete document'), ('restore_document', 'Can restore deleted document'), ('bulk_render', 'Can render multiple documents'))},
        ),
    ]
