# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_remove_soft_document_deletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisionakismetsubmission',
            name='revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='akismet_submissions', to='wiki.Revision', verbose_name='Revision'),
        ),
    ]
