# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-08 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_bcsignal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='comment',
            field=models.TextField(),
        ),
    ]
