# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-11 09:26
from __future__ import unicode_literals

from django.db import migrations


def change_locale_bn_bd_to_bn_and_remove_bn_inforwards(apps, schema_editor):
    Document = apps.get_model('wiki', 'Document')
    DocumentDeletionLog = apps.get_model('wiki', 'DocumentDeletionLog')

    Document.objects.all().filter(locale='bn-BD').update(locale='bn')
    DocumentDeletionLog.objects.all().filter(locale='bn-BD').update(locale='bn')

    # Remove bn-IN
    Document.objects.all().filter(locale='bn-IN').delete()
    DocumentDeletionLog.objects.all().filter(locale='bn-IN').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20190708_1314'),
    ]

    operations = [
        migrations.RunPython(change_locale_bn_bd_to_bn_and_remove_bn_inforwards)
    ]
