# Generated by Django 1.11.23 on 2019-10-23 07:41


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0005_auto_20190805_0306"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="locale",
            field=models.CharField(
                choices=[
                    ("en-US", "English (US)"),
                    ("ar", "عربي"),
                    ("bg", "Български"),
                    ("bm", "Bamanankan"),
                    ("bn", "বাংলা"),
                    ("ca", "Català"),
                    ("de", "Deutsch"),
                    ("el", "Ελληνικά"),
                    ("es", "Español"),
                    ("fa", "فارسی"),
                    ("fi", "suomi"),
                    ("fr", "Français"),
                    ("he", "עברית"),
                    ("hi-IN", "हिन्दी (भारत)"),
                    ("hu", "magyar"),
                    ("id", "Bahasa Indonesia"),
                    ("it", "Italiano"),
                    ("ja", "日本語"),
                    ("kab", "Taqbaylit"),
                    ("ko", "한국어"),
                    ("ms", "Melayu"),
                    ("my", "မြန်မာဘာသာ"),
                    ("nl", "Nederlands"),
                    ("pl", "Polski"),
                    ("pt-BR", "Português (do\xa0Brasil)"),
                    ("pt-PT", "Português (Europeu)"),
                    ("ru", "Русский"),
                    ("sv-SE", "Svenska"),
                    ("th", "ไทย"),
                    ("tr", "Türkçe"),
                    ("uk", "Українська"),
                    ("vi", "Tiếng Việt"),
                    ("zh-CN", "中文 (简体)"),
                    ("zh-TW", "正體中文 (繁體)"),
                ],
                db_index=True,
                default="en-US",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="documentdeletionlog",
            name="locale",
            field=models.CharField(
                choices=[
                    ("en-US", "English (US)"),
                    ("ar", "عربي"),
                    ("bg", "Български"),
                    ("bm", "Bamanankan"),
                    ("bn", "বাংলা"),
                    ("ca", "Català"),
                    ("de", "Deutsch"),
                    ("el", "Ελληνικά"),
                    ("es", "Español"),
                    ("fa", "فارسی"),
                    ("fi", "suomi"),
                    ("fr", "Français"),
                    ("he", "עברית"),
                    ("hi-IN", "हिन्दी (भारत)"),
                    ("hu", "magyar"),
                    ("id", "Bahasa Indonesia"),
                    ("it", "Italiano"),
                    ("ja", "日本語"),
                    ("kab", "Taqbaylit"),
                    ("ko", "한국어"),
                    ("ms", "Melayu"),
                    ("my", "မြန်မာဘာသာ"),
                    ("nl", "Nederlands"),
                    ("pl", "Polski"),
                    ("pt-BR", "Português (do\xa0Brasil)"),
                    ("pt-PT", "Português (Europeu)"),
                    ("ru", "Русский"),
                    ("sv-SE", "Svenska"),
                    ("th", "ไทย"),
                    ("tr", "Türkçe"),
                    ("uk", "Українська"),
                    ("vi", "Tiếng Việt"),
                    ("zh-CN", "中文 (简体)"),
                    ("zh-TW", "正體中文 (繁體)"),
                ],
                db_index=True,
                default="en-US",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="documentspamattempt",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spam_attempts",
                to="wiki.Document",
                verbose_name="Document (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="documentspamattempt",
            name="slug",
            field=models.CharField(max_length=255, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="documentspamattempt",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="revision",
            name="is_mindtouch_migration",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Did this revision come from MindTouch?",
            ),
        ),
        migrations.AlterField(
            model_name="revisionakismetsubmission",
            name="revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="akismet_submissions",
                to="wiki.Revision",
                verbose_name="Revision",
            ),
        ),
        migrations.AlterField(
            model_name="revisionakismetsubmission",
            name="type",
            field=models.CharField(
                choices=[("spam", "Spam"), ("ham", "Ham")],
                db_index=True,
                max_length=4,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="revisionip",
            name="ip",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=40,
                null=True,
                verbose_name="IP address",
            ),
        ),
        migrations.AlterField(
            model_name="revisionip",
            name="referrer",
            field=models.TextField(
                blank=True, editable=False, verbose_name="HTTP Referrer"
            ),
        ),
        migrations.AlterField(
            model_name="revisionip",
            name="user_agent",
            field=models.TextField(
                blank=True, editable=False, verbose_name="User-Agent"
            ),
        ),
    ]
