# Generated by Django 2.2.16 on 2021-01-04 11:39

from django.db import migrations


def forward(apps, schema_editor):
    Switch = apps.get_model("waffle", "Switch")
    Switch.objects.filter(name="application_ACAO").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0007_view_document_permission"),
    ]

    operations = [migrations.RunPython(forward)]
