# Generated by Django 2.2.16 on 2021-01-14 11:22

from django.db import migrations


def forward(apps, schema_editor):
    Flag = apps.get_model("waffle", "Flag")
    Flag.objects.filter(
        name__in=[
            "spam_testing_mode",
            "spam_spammer_override",
            "spam_admin_override",
            "spam_submissions_enabled",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0011_auto_20210108_0416"),
    ]

    operations = [migrations.RunPython(forward)]
