# Generated by Django 2.2.16 on 2021-01-15 05:31

from django.db import migrations


def forward(apps, schema_editor):
    Flag = apps.get_model("waffle", "Flag")
    Flag.objects.filter(
        name__in=[
            "sg_task_completion",
            "contrib_beta",
            "recurring_payment_beta",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0012_auto_20210114_1122"),
    ]

    operations = [migrations.RunPython(forward)]
