# Generated by Django 2.2.16 on 2021-01-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0013_auto_20210115_0531"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BCSignal",
        ),
    ]
