# Generated by Django 2.2.16 on 2021-04-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0014_delete_bcsignal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="locale",
            field=models.CharField(
                choices=[
                    ("en-US", "English (US)"),
                    ("de", "Deutsch"),
                    ("es", "Español"),
                    ("fr", "Français"),
                    ("ja", "日本語"),
                    ("ko", "한국어"),
                    ("pl", "Polski"),
                    ("pt-BR", "Português (do\xa0Brasil)"),
                    ("ru", "Русский"),
                    ("zh-CN", "中文 (简体)"),
                    ("zh-TW", "正體中文 (繁體)"),
                ],
                db_index=True,
                default="en-US",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="documentdeletionlog",
            name="locale",
            field=models.CharField(
                choices=[
                    ("en-US", "English (US)"),
                    ("de", "Deutsch"),
                    ("es", "Español"),
                    ("fr", "Français"),
                    ("ja", "日本語"),
                    ("ko", "한국어"),
                    ("pl", "Polski"),
                    ("pt-BR", "Português (do\xa0Brasil)"),
                    ("ru", "Русский"),
                    ("zh-CN", "中文 (简体)"),
                    ("zh-TW", "正體中文 (繁體)"),
                ],
                db_index=True,
                default="en-US",
                max_length=7,
            ),
        ),
    ]
