---
- name: Install node dependencies
  npm: name={{ item.name }} version={{ item.version }} global=yes
  with_items:
    - {name: 'fibers', version: '1.0.15'}
    - {name: 'clean-css', version: '2.2.16'}
    - {name: 'csslint', version: '0.10.0'}
    - {name: 'jshint', version: '2.7.0'}
    - {name: 'node-sass', version: '4.3.0'}
    - {name: 'uglify-js', version: '2.4.13'}
    - {name: 'bower-installer', version: '1.2.0'}

- name: Node binary symlinks
  file:
    src: "/usr/bin/{{ item }}"
    path: "/usr/local/bin/{{ item }}"
    state: link
  with_items:
    - cleancss
    - node-sass
