---
- name: Install node dependencies
  npm: name={{ item.name }} version={{ item.version }} global=yes
  with_items:
    - {name: 'fibers', version: '1.0.10'}
    - {name: 'csslint', version: '0.10.0'}
    - {name: 'jshint', version: '2.7.0'}
    - {name: 'stylus', version: '0.49.2'}
    - {name: 'bower-installer', version: '1.2.0'}
    - {name: 'yuglify', version: '0.1.4'}

- name: Node binary symlinks
  file:
    src: "/usr/bin/{{ item }}"
    path: "/usr/local/bin/{{ item }}"
    state: link
  with_items:
    - stylus
