---
- name: Install virtualenv
  pip: name=virtualenv

- name: Install Python packages in virtualenv
  pip:
    requirements: "{{ item }}"
    virtualenv: "/home/vagrant/env"
    virtualenv_site_packages: yes
  with_items:
  - /home/vagrant/src/requirements/compiled.txt
  - /home/vagrant/src/requirements/dev.txt
  - /home/vagrant/src/requirements/docs.txt
  - /home/vagrant/src/requirements/default.txt

- name: Update ownership of virtualenv to vagrant
  file:
    owner: vagrant
    group: vagrant
    recurse: yes
    state: directory
    path: "/home/vagrant/env"
