---
- name: Install virtualenv
  pip: name=virtualenv

- name: Install pip
  pip:
    name: pip
    version: 8.0.2
    virtualenv: /home/vagrant/env

- name: Install Python dependencies in virtualenv
  pip:
    requirements: "{{ item }}"
    virtualenv: /home/vagrant/env
    with_items:
      - /home/vagrant/src/requirements/compiled.txt
      - /home/vagrant/src/requirements/docs.txt
      - /home/vagrant/src/requirements/default.txt
      - /home/vagrant/src/requirements/local.txt

- name: Update ownership of virtualenv to vagrant
  file:
    owner: vagrant
    group: vagrant
    recurse: yes
    state: directory
    path: /home/vagrant/env
