---
- name: Install virtualenv
  pip: name=virtualenv

- name: Install pip
  pip:
    name: pip
    version: 8.0.2
    virtualenv: /home/vagrant/env

- name: Install local dependencies in virtualenv
  pip:
    requirements: /home/vagrant/src/requirements/local.txt
    virtualenv: /home/vagrant/env

- name: Install documentation dependencies in virtualenv
  pip:
    requirements: /home/vagrant/src/requirements/docs.txt
    virtualenv: /home/vagrant/env

- name: Update ownership of virtualenv to vagrant
  file:
    owner: vagrant
    group: vagrant
    recurse: yes
    state: directory
    path: /home/vagrant/env
