from django.conf.urls import include, url
from django.views.generic import TemplateView

from kuma.attachments.feeds import AttachmentsFeed

from . import feeds
from . import views


# These patterns inherit (?P<document_path>[^\$]+).
document_patterns = [
    url(r'^$',
        views.document,
        name='wiki.document'),
    url(r'^\$revision/(?P<revision_id>\d+)$',
        views.revision,
        name='wiki.revision'),
    url(r'^\$history$',
        views.document_revisions,
        name='wiki.document_revisions'),
    url(r'^\$edit$',
        views.edit_document,
        name='wiki.edit_document'),
    url(r'^\$edit/(?P<revision_id>\d+)$',
        views.edit_document,
        name='wiki.new_revision_based_on'),
    url(r'^\$compare$',
        views.compare_revisions,
        name='wiki.compare_revisions'),
    url(r'^\$children$',
        views.get_children,
        name='wiki.get_children'),
    url(r'^\$flag',
        views.flag,
        name='wiki.flag_document'),
    url(r'^\$translate$',
        views.translate,
        name='wiki.translate'),
    url(r'^\$locales$',
        views.select_locale,
        name='wiki.select_locale'),
    url(r'^\$json$',
        views.json_view,
        name='wiki.json_slug'),
    url(r'^\$styles$',
        views.styles_view,
        name='wiki.styles'),
    url(r'^\$toc$',
        views.toc_view,
        name='wiki.toc'),
    url(r'^\$move$',
        views.move,
        name='wiki.move'),
    url(r'^\$quick-review$',
        views.quick_review,
        name='wiki.quick_review'),
    url(r'^\$samples/(?P<sample_id>.+)/files/(?P<attachment_id>\d+)/(?P<filename>.+)$',
        views.raw_code_sample_file,
        name='wiki.raw_code_sample_file'),
    url(r'^\$samples/(?P<sample_id>.+)$',
        views.code_sample,
        name='wiki.code_sample'),
    url(r'^\$revert/(?P<revision_id>\d+)$',
        views.revert_document,
        name='wiki.revert_document'),
    url(r'^\$repair_breadcrumbs$',
        views.repair_breadcrumbs,
        name='wiki.repair_breadcrumbs'),
    url(r'^\$delete$',
        views.delete_document,
        name='wiki.delete_document'),
    url(r'^\$restore$',
        views.restore_document,
        name='wiki.restore_document'),
    url(r'^\$purge$',
        views.purge_document,
        name='wiki.purge_document'),

    # Un/Subscribe to document edit notifications.
    url(r'^\$subscribe$',
        views.subscribe_document,
        name='wiki.subscribe_document'),

    # Vote helpful/not helpful
    url(r'^\$vote',
        views.helpful_vote,
        name="wiki.document_vote"),
]

urlpatterns = [
    # Un/Subscribe to locale 'ready for review' notifications.
    url(r'^/ckeditor_config.js$',
        views.ckeditor_config,
        name='wiki.ckeditor_config'),

    # internals
    url(r'^.json$',
        views.json_view,
        name='wiki.json'),
    url(r'^/preview-wiki-content$',
        views.preview_revision,
        name='wiki.preview'),
    url(r'^/move-requested$',
        TemplateView.as_view(
            template_name='wiki/move_requested.html'),
        name='wiki.move_requested'),
    url(r'^/get-documents$',
        views.autosuggest_documents,
        name='wiki.autosuggest_documents'),
    url(r'^/load/$', 'load_documents', name='wiki.load_documents'),

    # Special pages
    url(r'^/templates$',
        views.list_templates,
        name='wiki.list_templates'),
    url(r'^/tags$',
        views.list_tags,
        name='wiki.list_tags'),
    url(r'^/tag/(?P<tag>.+)$',
        views.list_documents,
        name='wiki.tag'),
    url(r'^/new$',
        views.new_document,
        name='wiki.new_document'),
    url(r'^/all$',
        views.list_documents,
        name='wiki.all_documents'),
    url(r'^/with-errors$',
        views.list_documents_with_errors,
        name='wiki.errors'),
    url(r'^/without-parent$',
        views.list_documents_without_parent,
        name='wiki.without_parent'),
    url(r'^/top-level$',
        views.list_top_level_documents,
        name='wiki.top_level'),
    url(r'^/needs-review/(?P<tag>[^/]+)$',
        views.list_documents_for_review,
        name='wiki.list_review_tag'),
    url(r'^/needs-review/?',
        views.list_documents_for_review,
        name='wiki.list_review'),
    url(r'^/localization-tag/(?P<tag>[^/]+)$',
        views.list_documents_with_localization_tag,
        name='wiki.list_with_localization_tag'),
    url(r'^/localization-tag/?',
        views.list_documents_with_localization_tag,
        name='wiki.list_with_localization_tags'),
    url(r'^/category/(?P<category>\d+)$',
        views.list_documents,
        name='wiki.category'),

    # Feeds
    url(r'^/feeds/(?P<format>[^/]+)/all/?',
        feeds.DocumentsRecentFeed(),
        name="wiki.feeds.recent_documents"),
    url(r'^/feeds/(?P<format>[^/]+)/l10n-updates/?',
        feeds.DocumentsUpdatedTranslationParentFeed(),
        name="wiki.feeds.l10n_updates"),
    url(r'^/feeds/(?P<format>[^/]+)/tag/(?P<tag>[^/]+)',
        feeds.DocumentsRecentFeed(),
        name="wiki.feeds.recent_documents"),
    url(r'^/feeds/(?P<format>[^/]+)/category/(?P<category>[^/]+)',
        feeds.DocumentsRecentFeed(),
        name="wiki.feeds.recent_documents_category"),
    url(r'^/feeds/(?P<format>[^/]+)/needs-review/(?P<tag>[^/]+)',
        feeds.DocumentsReviewFeed(),
        name="wiki.feeds.list_review_tag"),
    url(r'^/feeds/(?P<format>[^/]+)/needs-review/?',
        feeds.DocumentsReviewFeed(),
        name="wiki.feeds.list_review"),
    url(r'^/feeds/(?P<format>[^/]+)/revisions/?',
        feeds.RevisionsFeed(),
        name="wiki.feeds.recent_revisions"),
    url(r'^/feeds/(?P<format>[^/]+)/files/?',
        AttachmentsFeed(),
        name="attachments.feeds.recent_files"),

    url(r'^/(?P<document_path>[^\$]+)', include(document_patterns)),
]
