/**
 * @license Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.html or http://ckeditor.com/license
 */

var CKBUILDER_CONFIG = {
	skin: 'moono',
	ignore: [
		'bender.js',
		'.bender',
		'bender-err.log',
		'bender-out.log',
		'dev',
		'.DS_Store',
		'.gitignore',
		'.gitattributes',
		'Gruntfile.js',
		'.idea',
		'.jscsrc',
		'.jshintignore',
		'.jshintrc',
		'.mailmap',
		'node_modules',
		'package.json',
		'README.md',
		'tests'
	],

	/* Should be kept in sync with the list in ckeditor_config.js. */
	plugins: {
		a11yhelp: 1,
		autogrow: 1,
		basicstyles: 1,
		bidi: 1,
		blockquote: 1,
		clipboard: 1,
		contextmenu: 1,
		dialogadvtab: 1,
		elementspath: 1,
		enterkey: 1,
		entities: 1,
		find: 1,
		htmlwriter: 1,
		image: 1,
		indentlist: 1,
		language: 1,
		link: 1,
		list: 1,
		liststyle: 1,
		magicline: 1,
		maximize: 1,
		pastefromword: 1,
		pastetext: 1,
		removeformat: 1,
		resize: 1,
		scayt: 1,
		sharedspace: 1,
		showblocks: 1,
		showborders: 1,
		sourcearea: 1,
		stylescombo: 1,
		tab:1,
		table: 1,
		tabletools: 1,
		toolbar: 1,
		undo: 1,
		wsc: 1,
		wysiwygarea: 1,
		'mdn-attachment': 1,
		'mdn-format': 1,
		'mdn-sticky-toolbar': 1,
		'mdn-image-attachment': 1,
		'mdn-link-customization': 1,
		'mdn-link-launch': 1,
		'mdn-redirect': 1,
		'mdn-sample-finder': 1,
		'mdn-sampler': 1,
		'mdn-spell': 1,
		'mdn-syntaxhighlighter': 1,
		'mdn-system-integration': 1,
		'mdn-table-customization': 1,
		'mdn-toggle-block': 1,
		'mdn-wrapstyle': 1,
		'mdn-youtube': 1,
		descriptionlist: 1,
		tablesort: 1,
		texzilla: 1
	}
};
