# See https://docs.codecov.io/docs/pull-request-comments
comment:
  # layout: "reach, diff, flags, files"
  layout: "diff, flags, files"
  # behavior: default
  require_changes: true  # if true: only post the comment if coverage changes
