coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.01%
        only_pulls: true

# See https://docs.codecov.io/docs/pull-request-comments
comment:
  # layout: "reach, diff, flags, files"
  layout: "diff, flags, files"
  require_changes: true  # if true: only post the comment if coverage changes
