# This is a work in progress.
#
# The preferred way to set up development is still using Vagrant as documented here:
# http://kuma.readthedocs.org/en/latest/installation.html

FROM quay.io/deis/base:0.2.0

ENV PYTHONDONTWRITEBYTECODE=1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /app
EXPOSE 8000

RUN apt-get update && \
    apt-get install -y --no-install-recommends python2.7 libpython2.7 python-dev \
    python-pip python-setuptools gettext build-essential \
    nodejs npm \
    libtidy-0.99-0 libtidy-dev \
    libxml2-dev libxslt1.1 libxslt1-dev \
    libffi-dev \
    libjpeg-dev \
    libmagic-dev \
    libmysqlclient-dev \
    mysql-client  # Only for local dev.
RUN update-alternatives --install /usr/bin/node node /usr/bin/nodejs 10

RUN npm install -g \
    fibers@1.0.13 \
    clean-css@2.2.16 \
    csslint@0.10.0 \
    jshint@2.7.0 \
    stylus@0.49.2 \
    uglify-js@2.4.13

COPY ./requirements /app/requirements
RUN pip install --no-cache-dir -r requirements/local.txt
# TODO: add supervisor to requirements/local.txt
RUN pip install supervisor
