# Generated by Django 2.2.16 on 2021-03-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0003_auto_20191023_0405"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="filtergroup",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="outdatedobject",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="outdatedobject",
            name="index",
        ),
        migrations.DeleteModel(
            name="Filter",
        ),
        migrations.DeleteModel(
            name="FilterGroup",
        ),
        migrations.DeleteModel(
            name="Index",
        ),
        migrations.DeleteModel(
            name="OutdatedObject",
        ),
    ]
