VERIFY_URL = '/1.1/verify-key'
CHECK_URL = '/1.1/comment-check'
SPAM_URL = '/1.1/submit-spam'
HAM_URL = '/1.1/submit-ham'

SPAM_CHECKS_FLAG = 'spam_checks_enabled'
SPAM_SUBMISSIONS_FLAG = 'spam_submissions_enabled'
SPAM_ADMIN_FLAG = 'spam_admin_override'
SPAM_SPAMMER_FLAG = 'spam_spammer_override'
SPAM_TESTING_FLAG = 'spam_testing_mode'
