# Generated by Django 2.2.21 on 2021-05-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_create_common_survey_banner_switch"),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS feeder_entry"),
        migrations.RunSQL("DROP TABLE IF EXISTS feeder_bundle_feeds"),
        migrations.RunSQL("DROP TABLE IF EXISTS feeder_feed"),
        migrations.RunSQL("DROP TABLE IF EXISTS feeder_bundle"),
    ]
