# Generated by Django 2.2.21 on 2021-05-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_delete_feeder_data"),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS soapbox_message"),
    ]
