# Generated by Django 2.2.21 on 2021-06-24 13:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documenturls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='User ID')),
                ('notes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('deleted', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('documenturl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documenturls.DocumentURL', verbose_name='Document URL')),
            ],
            options={
                'verbose_name': 'Bookmark',
                'unique_together': {('documenturl', 'user_id')},
            },
        ),
    ]
