# Generated by Django 3.2.5 on 2021-07-12 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documenturls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.PositiveIntegerField(verbose_name="User ID")),
                ("notes", models.JSONField(default=list)),
                ("deleted", models.DateTimeField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "documenturl",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documenturls.documenturl",
                        verbose_name="Document URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bookmark",
                "unique_together": {("documenturl", "user_id")},
            },
        ),
    ]
