# Generated by Django 3.2.10 on 2022-01-18 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmark",
            name="notes",
        ),
    ]
