# Generated by Django 3.2.10 on 2022-01-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0002_remove_bookmark_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="custom_name",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="notes",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
