INSERT INTO taggit_tag (name, slug) VALUES ('Windows 3.11', 'windows-311') ON DUPLICATE KEY UPDATE name='Windows 3.11', slug='windows-311';
INSERT INTO taggit_tag (name, slug) VALUES ('Windows 95', 'windows-95') ON DUPLICATE KEY UPDATE name='Windows 95', slug='windows-95';
INSERT INTO taggit_tag (name, slug) VALUES ('Windows 98', 'windows-98') ON DUPLICATE KEY UPDATE name='Windows 98', slug='windows-98';
INSERT INTO taggit_tag (name, slug) VALUES ('Windows 2000', 'windows-2000') ON DUPLICATE KEY UPDATE name='Windows 2000', slug='windows-2000';
INSERT INTO taggit_tag (name, slug) VALUES ('Windows XP', 'windows-xp') ON DUPLICATE KEY UPDATE name='Windows XP', slug='windows-xp';
INSERT INTO taggit_tag (name, slug) VALUES ('Windows Server 2003', 'windows-server-2003') ON DUPLICATE KEY UPDATE name='Windows Server 2003', slug='windows-server-2003';
INSERT INTO taggit_tag (name, slug) VALUES ('Windows Vista', 'windows-vista') ON DUPLICATE KEY UPDATE name='Windows Vista', slug='windows-vista';
INSERT INTO taggit_tag (name, slug) VALUES ('Windows 7', 'windows-7') ON DUPLICATE KEY UPDATE name='Windows 7', slug='windows-7';
INSERT INTO taggit_tag (name, slug) VALUES ('Windows NT 4.0', 'windows-nt-40') ON DUPLICATE KEY UPDATE name='Windows NT 4.0', slug='windows-nt-40';
INSERT INTO taggit_tag (name, slug) VALUES ('Windows ME', 'windows-me') ON DUPLICATE KEY UPDATE name='Windows ME', slug='windows-me';
INSERT INTO taggit_tag (name, slug) VALUES ('Windows', 'windows') ON DUPLICATE KEY UPDATE name='Windows', slug='windows';
INSERT INTO taggit_tag (name, slug) VALUES ('OpenBSD', 'openbsd') ON DUPLICATE KEY UPDATE name='OpenBSD', slug='openbsd';
INSERT INTO taggit_tag (name, slug) VALUES ('SunOS', 'sunos') ON DUPLICATE KEY UPDATE name='SunOS', slug='sunos';
INSERT INTO taggit_tag (name, slug) VALUES ('Linux', 'linux') ON DUPLICATE KEY UPDATE name='Linux', slug='linux';
INSERT INTO taggit_tag (name, slug) VALUES ('Mac OS X 10.4', 'mac-os-x-104') ON DUPLICATE KEY UPDATE name='Mac OS X 10.4', slug='mac-os-x-104';
INSERT INTO taggit_tag (name, slug) VALUES ('Mac OS X 10.5', 'mac-os-x-105') ON DUPLICATE KEY UPDATE name='Mac OS X 10.5', slug='mac-os-x-105';
INSERT INTO taggit_tag (name, slug) VALUES ('Mac OS X 10.6', 'mac-os-x-106') ON DUPLICATE KEY UPDATE name='Mac OS X 10.6', slug='mac-os-x-106';
INSERT INTO taggit_tag (name, slug) VALUES ('Mac OS', 'mac-os') ON DUPLICATE KEY UPDATE name='Mac OS', slug='mac-os';
INSERT INTO taggit_tag (name, slug) VALUES ('QNX', 'qnx') ON DUPLICATE KEY UPDATE name='QNX', slug='qnx';
INSERT INTO taggit_tag (name, slug) VALUES ('BeOS', 'beos') ON DUPLICATE KEY UPDATE name='BeOS', slug='beos';
INSERT INTO taggit_tag (name, slug) VALUES ('OS/2', 'os2') ON DUPLICATE KEY UPDATE name='OS/2', slug='os2';
