INSERT INTO inproduct_redirect
(product, version, platform, locale, topic, target)
VALUES
('mobile', '', '', '', '', 'http://www.mozilla.com/m/support'),
('mobile', '', '', '', 'firefox-help', 'http://www.mozilla.com/m/support'),
('', '', 'iPhone', '', '', 'kb/What is Firefox Home'),
('', '', '', '', '', 'home'),
('', '', 'iPhone', '', 'install', 'kb/How to set up Firefox Home'),
('', '', '', '', 'pageinfo_general', 'kb/Page Info window'),
('', '', '', '', 'pageinfo_media', 'kb/Page Info window#Media'),
('', '', '', '', 'pageinfo_feed', 'kb/Page Info window#Feeds'),
('', '', '', '', 'pageinfo_permissions', 'kb/Page Info window#Permissions'),
('', '', '', '', 'pageinfo_security', 'kb/Page Info window#Security'),
('', '', '', '', 'prefs-weave', 'kb/How to sync Firefox settings between computers'),
('', '', '', '', 'plugin-crashed', 'kb/Plugin crash reports'),
('', '', '', '', 'firefox-help', 'home'),
('', '', '', '', 'firefox-f1', 'home'),
('', '', '', '', 'firefox-osxkey', 'home'),
('', '', '', '', 'keyboard-shortcuts', 'kb/Keyboard shortcuts'),
('', '', '', '', 'prefs-main', 'kb/Options window - General panel'),
('', '', '', '', 'prefs-clear-private-data', 'kb/Clear Recent History'),
('', '', '', '', 'prefs-fonts-and-colors', 'kb/Options window - Content panel#fonts_and_colors'),
('', '', '', '', 'prefs-privacy', 'kb/Options window - Privacy panel'),
('', '', '', '', 'prefs-applications', 'kb/Options window - Applications panel'),
('', '', '', '', 'prefs-connection-settings', 'kb/Options window - Advanced panel#connection_settings'),
('', '', '', '', 'prefs-tabs', 'kb/Options window - Tabs panel'),
('', '', '', '', 'prefs-advanced-javascript', 'kb/Options window - Content panel'),
('', '', '', '', 'prefs-languages', 'kb/Options window - Content panel#languages'),
('', '', '', '', 'prefs-content', 'kb/Options window - Content panel'),
('', '', '', '', 'prefs-security', 'kb/Options window - Security panel'),
('', '', '', '', 'prefs-advanced-general', 'kb/Options window - Advanced panel'),
('', '', '', '', 'prefs-advanced-network', 'kb/Options window - Advanced panel#advanced_network'),
('', '', '', '', 'prefs-advanced-update', 'kb/Options window - Advanced panel#advanced_update'),
('', '', '', '', 'prefs-advanced-encryption', 'kb/Options window - Advanced panel#advanced_encryption'),
('', '', '', '', 'ieusers', 'kb/Windows start page'),
('', '', '', '', 'places-locked', 'kb/The bookmarks and history system will not be functional'),
('', '', '', '', 'private-browsing', 'kb/Private Browsing'),
('firefox-home', '', 'iPhone', '', 'log-in', 'kb/Cannot log in to Firefox Home App');
