// @flow
import * as React from 'react';

import A11yNav from '../a11y/a11y-nav.jsx';
import Header from '../header/header.jsx';
import UserProvider from '../user-provider.jsx';

/**
 * This is the React component that we use for the React user account page.
 * Most of the user account page components are still generated by Kuma and
 * Jinja templates. All we're doing here is rendering the page header with
 * menus, search and sign in / sign out features.
 *
 * This will then also serve as the basis for building out the full user
 * account page in React.
 */
export default function UserAccount() {
    return (
        <UserProvider>
            <A11yNav />
            <Header />
        </UserProvider>
    );
}
