// @flow
import * as React from 'react';

import Banners from './banners.jsx';
import GAProvider from './ga-provider.jsx';
import Header from './header/header.jsx';
import UserProvider from './user-provider.jsx';

/**
 * This is the React component that we use for the React homepage.
 * Most of the homepage is still generated by Kuma and Jinja templates.
 * All we're doing here is rendering the page header with menus, search
 * and sign in / sign out features.
 */
export default function LandingPage() {
    return (
        <GAProvider>
            <UserProvider>
                <Header />
                <Banners />
            </UserProvider>
        </GAProvider>
    );
}
