// @flow
import * as React from 'react';

import A11yNav from './a11y/a11y-nav.jsx';
import Header from './header/header.jsx';
import UserProvider from './user-provider.jsx';

/**
 * This is the React component that we use for the React sign-up flow.
 * Most of the sign-up flow is still generated by Kuma and Jinja templates.
 * All we're doing here is rendering the page header with menus, search
 * and sign in / sign out features.
 */
export default function SignupFlow() {
    return (
        <UserProvider>
            <A11yNav />
            <Header />
        </UserProvider>
    );
}
