# Generated by Django 2.2.21 on 2021-06-24 13:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=250, unique=True, verbose_name='URI')),
                ('absolute_url', models.URLField(verbose_name='Absolute URL')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('invalid', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document URL',
            },
        ),
        migrations.CreateModel(
            name='DocumentURLCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_error', models.IntegerField(verbose_name='HTTP error')),
                ('headers', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('document_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documenturls.DocumentURL', verbose_name='Document URL')),
            ],
            options={
                'verbose_name': 'Document URL Check',
            },
        ),
    ]
