# Generated by Django 3.2.5 on 2021-07-12 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uri",
                    models.CharField(max_length=250, unique=True, verbose_name="URI"),
                ),
                ("absolute_url", models.URLField(verbose_name="Absolute URL")),
                ("metadata", models.JSONField(null=True)),
                ("invalid", models.DateTimeField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Document URL",
            },
        ),
        migrations.CreateModel(
            name="DocumentURLCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("http_error", models.IntegerField(verbose_name="HTTP error")),
                ("headers", models.JSONField(default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "document_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documenturls.documenturl",
                        verbose_name="Document URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document URL Check",
            },
        ),
    ]
