# Generated by Django 2.2.21 on 2021-05-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0002_auto_20191023_0405'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='entry',
            name='feed',
        ),
        migrations.DeleteModel(
            name='Bundle',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
