# Generated by Django 3.2.7 on 2021-10-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20211014_1214"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="fxa_uid",
        ),
    ]
