# Generated by Django 3.2.7 on 2021-12-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_userprofile_fxa_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_subscriber",
            field=models.BooleanField(default=False),
        ),
    ]
