# Generated by Django 3.2.10 on 2021-12-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userprofile_is_subscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("fxa_uid", models.CharField(blank=True, default="", max_length=128)),
                ("payload", models.TextField(blank=True, default="", max_length=2048)),
                (
                    "event_type",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Password Changed"),
                            (2, "Profile Changed"),
                            (3, "Subscription Changed"),
                            (4, "Profile Deleted"),
                        ],
                        default="",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Processed"),
                            (2, "Pending"),
                            (3, "Ignored"),
                            (4, "Not Implemented"),
                        ],
                        default=2,
                    ),
                ),
                ("jwt_id", models.CharField(blank=True, default="", max_length=256)),
                ("issued_at", models.CharField(blank=True, default="", max_length=32)),
            ],
            options={
                "ordering": ["-modified_at"],
            },
        ),
    ]
