# Generated by Django 3.2.10 on 2022-03-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_accountevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="subscription_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mdn_plus_5m", "MDN Plus 5M"),
                    ("mdn_plus_5y", "MDN Plus 5Y"),
                    ("mdn_plus_10m", "MDN Plus 10M"),
                    ("mdn_plus_10y", "MDN Plus 10Y"),
                    ("", "None"),
                ],
                default="",
                max_length=512,
            ),
        ),
    ]
