# Generated by Django 1.11.23 on 2019-09-12 16:34


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_merge_bn_bd_and_bn_in_to_bn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="locale",
            field=models.CharField(
                blank=True,
                choices=[
                    (b"en-US", "English (US)"),
                    (b"af", "Afrikaans"),
                    (b"ar", "\u0639\u0631\u0628\u064a"),
                    (b"az", "Az\u0259rbaycanca"),
                    (b"bg", "\u0411\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438"),
                    (b"bm", "Bamanankan"),
                    (b"bn", "\u09ac\u09be\u0982\u09b2\u09be"),
                    (b"ca", "Catal\xe0"),
                    (b"cs", "\u010ce\u0161tina"),
                    (b"de", "Deutsch"),
                    (b"ee", "E\u028be"),
                    (b"el", "\u0395\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac"),
                    (b"es", "Espa\xf1ol"),
                    (b"fa", "\u0641\u0627\u0631\u0633\u06cc"),
                    (b"ff", "Pulaar-Fulfulde"),
                    (b"fi", "suomi"),
                    (b"fr", "Fran\xe7ais"),
                    (b"fy-NL", "Frysk"),
                    (b"ga-IE", "Gaeilge"),
                    (b"ha", "Hausa"),
                    (b"he", "\u05e2\u05d1\u05e8\u05d9\u05ea"),
                    (
                        b"hi-IN",
                        "\u0939\u093f\u0928\u094d\u0926\u0940 (\u092d\u093e\u0930\u0924)",
                    ),
                    (b"hr", "Hrvatski"),
                    (b"hu", "magyar"),
                    (b"id", "Bahasa Indonesia"),
                    (b"ig", "Igbo"),
                    (b"it", "Italiano"),
                    (b"ja", "\u65e5\u672c\u8a9e"),
                    (b"ka", "\u10e5\u10d0\u10e0\u10d7\u10e3\u10da\u10d8"),
                    (b"kab", "Taqbaylit"),
                    (b"ko", "\ud55c\uad6d\uc5b4"),
                    (b"ln", "Ling\xe1la"),
                    (b"mg", "Malagasy"),
                    (b"ml", "\u0d2e\u0d32\u0d2f\u0d3e\u0d33\u0d02"),
                    (b"ms", "Melayu"),
                    (
                        b"my",
                        "\u1019\u103c\u1014\u103a\u1019\u102c\u1018\u102c\u101e\u102c",
                    ),
                    (b"nl", "Nederlands"),
                    (b"pl", "Polski"),
                    (b"pt-BR", "Portugu\xeas (do\xa0Brasil)"),
                    (b"pt-PT", "Portugu\xeas (Europeu)"),
                    (b"ro", "Rom\xe2n\u0103"),
                    (b"ru", "\u0420\u0443\u0441\u0441\u043a\u0438\u0439"),
                    (b"son", "So\u014bay"),
                    (b"sq", "Shqip"),
                    (b"sr", "\u0421\u0440\u043f\u0441\u043a\u0438"),
                    (b"sr-Latn", "Srpski"),
                    (b"sv-SE", "Svenska"),
                    (b"sw", "Kiswahili"),
                    (b"ta", "\u0ba4\u0bae\u0bbf\u0bb4\u0bcd"),
                    (b"te", "\u0c24\u0c46\u0c32\u0c41\u0c17\u0c41"),
                    (b"th", "\u0e44\u0e17\u0e22"),
                    (b"tl", "Tagalog"),
                    (b"tn", "Setswana"),
                    (b"tr", "T\xfcrk\xe7e"),
                    (
                        b"uk",
                        "\u0423\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430",
                    ),
                    (b"vi", "Ti\u1ebfng Vi\u1ec7t"),
                    (b"wo", "Wolof"),
                    (b"xh", "isiXhosa"),
                    (b"yo", "Yor\xf9b\xe1"),
                    (b"zh-CN", "\u4e2d\u6587 (\u7b80\u4f53)"),
                    (b"zh-TW", "\u6b63\u9ad4\u4e2d\u6587 (\u7e41\u9ad4)"),
                    (b"zu", "isiZulu"),
                ],
                db_index=True,
                default=b"en-US",
                max_length=7,
                verbose_name="Language",
            ),
        ),
    ]
