# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-04 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191023_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salesforce_connection',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('success', 'success'), ('error', 'error')], max_length=10, null=True),
        ),
    ]
