# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-10 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_auto_20191023_0741"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_newsletter_subscribed",
            field=models.BooleanField(default=False),
        ),
    ]
