# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-03 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200110_0519'),
        ('users', '0014_user_is_newsletter_subscribed'),
    ]

    operations = [
    ]
