# Generated by Django 2.2.11 on 2020-03-30 07:17

from django.db import migrations, models


def set_initial_subscriber_number(apps, schema_editor):
    User = apps.get_model("users", "User")
    number = 1
    for user in User.objects.exclude(
        stripe_customer_id="", subscriber_number__isnull=True
    ):
        user.subscriber_number = number
        user.save()
        number += 1


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_usersubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscriber_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(set_initial_subscriber_number),
    ]
