#!/bin/bash
set -e  # Exit on non-zero status
set -u  # Treat unset variables as an error

# Note! The reason why this is done *outside* docker-compose is that
# `eslint` can't cope with the fact that `node_modules` isn't in `./`.
# Inside docker we move $NODE_PATH to /tool/node_modules and when
# you attempt to run `eslint` with the source files, it will fail
# because it can't find dependencies.
# In conclusion, only do this bash script for testing non-runtime things
# like linting. JavaScript unit test running related tasks do not
# belong in this file.
make jslint
