#!/bin/bash
set -e  # Exit on non-zero status
set -u  # Treat unset variables as an error

# XXX Instead of using the "make-bundle" `localerefresh` we spell out
# each and every one of these. Otherwise it causes to build-static again.
## docker-compose exec -T web make localerefresh
docker-compose exec -T web make localeextract
docker-compose exec -T web make localetest
docker-compose exec -T web make localecompile

cd locale
export GIT_PAGER=cat
git diff -G "^msgid " templates/LC_MESSAGES
