#!/bin/bash
set -e  # Exit on non-zero status
set -u  # Treat unset variables as an error

# This script checks if the dependencies in `package.json` were manually
# edited as opposed to being done with `yarn add/remove ...`
git status -s
git status -s | wc -c | awk '{$1=$1};1'
