#!/bin/bash

# The Stylus executable resides in /usr/local/bin on our public servers. For
# this script to work correctly on those servers, we need to include the
# directory in our PATH.
#
# See: https://bugzilla.mozilla.org/show_bug.cgi?id=1092364
PATH=/usr/local/bin:$PATH

BASEDIR=$(dirname $0)
CSSDIR=$BASEDIR/../media/css
STYLUSDIR=$BASEDIR/../media/stylus

for opt in "$@"; do
  case $opt in
    --watch|-w) WATCH=true;;
    --quiet|-q) QUIET=true;;
  esac
done

if [ ! -d "$CSSDIR" ]; then
  mkdir $CSSDIR
fi

STYLESHEETS=($STYLUSDIR/*.styl)
if [ $WATCH ]; then
  echo Watching and automatically compiling stylesheets

  # Using $STYLESHEETS directly so that stylus only watches each stylesheet
  # once, even if it is @included multiple times.
  if [ $QUIET ]; then
    (stylus ${STYLESHEETS[@]} --out $CSSDIR --compress --watch &) &> /dev/null
  else
    stylus ${STYLESHEETS[@]} --out $CSSDIR --compress --watch
  fi
else
  # Iterating through stylesheets so that shell output is immediate.
  for ss in ${STYLESHEETS[@]}; do
    stylus $ss --out $CSSDIR --compress
  done
fi
