#!/bin/bash
set -e  # Exit on non-zero status
set -u  # Treat unset variables as an error

gunicorn -w ${GUNICORN_WORKERS:-4} --bind 0.0.0.0:8000 --access-logfile=- --timeout=120 kuma.wsgi:application
