
# A script to generate a template which will be used to localize the supported locale name
# For more inofrmation see https://bugzil.la/859499#c11

from django.conf import settings

from jinja2 import Environment


template_string = ("""

This template is automatically generated by scripts/translate_locales.py to make the languages name localizable. Do not edit it manually
Background: https://bugzil.la/859499#c11

{% for lang in languages %}
   {{ '{{ _("' + lang + '") }}' }}
{% endfor %}

""")


LANGUAGES = sorted([lang_info.english.encode('ascii', 'ignore')
                    for lang_code, lang_info in settings.LOCALES.items()
                    if lang_code in settings.MDN_LANGUAGES])

string = Environment().from_string(template_string).render(languages=LANGUAGES)

jinja_path = settings.TEMPLATES[0]["DIRS"][0]
template_path = jinja_path + '/includes/translate_locales.html'

outfile = open(template_path, "w")
outfile.write(string)
outfile.close()
