#!/bin/bash
set -e  # Exit on non-zero status
set -x  # Print commands run
set -u  # Treat unset variables as an error

export LC_CTYPE=en_US.UTF-8

if [ -x $(command -v docker-compose) ]
then
    echo "Overwriting existing docker-compose."
    docker-compose -v
else
    echo "Installing docker-compose ${DOCKER_COMPOSE_VERSION}."
fi
mkdir -p downloads
DOCKER_COMPOSE_FILE=downloads/docker-compose-${DOCKER_COMPOSE_VERSION}
if [ ! -f $DOCKER_COMPOSE_FILE ]
then
    wget -q --waitretry=1 --retry-connrefused -T 10 \
        -O downloads/docker-compose-${DOCKER_COMPOSE_VERSION} \
        https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m`
fi
chmod +x $DOCKER_COMPOSE_FILE
sudo cp $DOCKER_COMPOSE_FILE /usr/local/bin/docker-compose
