#!/bin/bash
set -e
set -x
export LC_CTYPE=en_US.UTF-8

if [ "$TOXENV" == "py27" ]
then
    sudo apt-get update -qq
    sudo apt-get -y install build-essential libxml2-dev libxslt-dev libjpeg8 libjpeg8-dev libfreetype6 libfreetype6-dev zlib1g-dev sqlite3 tidy libtidy-dev libtidy-0.99-0 python-dev libffi-dev libssl-dev
    sudo ln -s /usr/lib/`uname -i`-linux-gnu/libfreetype.so /usr/lib
    sudo ln -s /usr/lib/`uname -i`-linux-gnu/libz.so /usr/lib

    # completely and utterly remove Travis' MySQL and let the Ansible role install it
    sudo apt-get remove --purge 'mysql*'
    sudo apt-get autoremove
    sudo apt-get autoclean
    sudo rm -rf /var/lib/mysql
    sudo rm -rf /var/lib/mysql-5.6
    sudo rm -rf /run/mysql
    sudo rm -rf /run/mysql-5.6
    sudo rm -rf /etc/mysql
    sudo rm -rf /etc/mysql-5.6
    sudo rm -rf /var/log/mysql
    sudo rm -rf /var/log/mysql-5.6
    sudo rm -f /etc/init/mysql-5.6.conf
    sudo rm -f /etc/init/mysql.conf
    sudo rm -f /etc/init.d/mysql

    # Install Elasticsearch
    wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.2.deb
    sudo dpkg -i elasticsearch-1.7.2.deb

    # limit elasticsearch / java memory usage to avoid OOM Killer
    sudo service elasticsearch stop;
    echo "ES_HEAP_SIZE=256m" | sudo tee --append /etc/default/elasticsearch
    sudo service elasticsearch start;
fi

if [ "$TOXENV" == "docker" -o "$TOXENV" == "locales" ]
then
    curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    chmod +x docker-compose
    sudo mv docker-compose /usr/local/bin
fi

# Debug failures on Dec 1 2016
if [ "$TOXENV" == "py27" ]
then
    pip install -r requirements/travis.txt
    ansible-playbook -vvv --tags=mysql,pipeline --connection=local --inventory-file=provisioning/inventory provisioning/travis.yml || touch /tmp/provision_failed
    if [ -e /tmp/provision_failed ]
    then
        sudo cat /var/log/mysql/error.log || echo "No such file"
        sudo cat /var/log/mysql-5.6/error.log || echo "No such file"
        # Maybe https://github.com/travis-ci/travis-ci/issues/6842 ?
        sudo ls /run
        sudo ls /run/mysql-5.6
        sudo ls /var/run

        sudo ls /etc/init.d
        sudo cat /etc/init.d/mysql || echo "No such file"
        sudo ls /etc/init
        sudo cat /etc/init/mysql-5.6.conf || echo "No such file"
        sudo my_print_defaults mysqld_safe || echo "mysqd_safe failed"
        sudo my_print_defaults mysqld || echo "mysql failed"

        sudo cat /etc/mysql-5.6/my.cnf || echo "No such file"
        exit 1
    fi
fi
