#!/bin/bash
set -e
set -x
export LC_CTYPE=en_US.UTF-8

if [ "$TOXENV" == "py27" ]
then
    sudo apt-get update -qq
    sudo apt-get -y install build-essential libxml2-dev libxslt-dev libjpeg8 libjpeg8-dev libfreetype6 libfreetype6-dev zlib1g-dev sqlite3 tidy libtidy-dev libtidy-0.99-0
    sudo ln -s /usr/lib/`uname -i`-linux-gnu/libfreetype.so /usr/lib
    sudo ln -s /usr/lib/`uname -i`-linux-gnu/libz.so /usr/lib

    # product details & locales
    tar -C .. -zxf etc/data/product_details_json.tar.gz
    tar xvfz etc/data/locale.tar.gz

    # elasticsearch
    curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.7.deb
    sudo dpkg --force-confdef -i elasticsearch-1.3.7.deb
    sudo service elasticsearch start

    # completely and utterly remove Travis' MySQL and let the Ansible role install it
    sudo apt-get remove --purge 'mysql*'
    sudo apt-get autoremove
    sudo apt-get autoclean
    sudo rm -rf /var/lib/mysql
    sudo truncate -s 0 /var/log/mysql/error.log

fi
