---
- hosts: all
  gather_facts: yes
  sudo: true
  vars_files:
    - vars/apache.yml
    - vars/elasticsearch.yml
    - vars/mysql.yml
    - vars/rabbitmq.yml
  roles:
    - geerlingguy.memcached
    - geerlingguy.mysql
    - geerlingguy.apache
    - Mayeu.RabbitMQ
    - Stouts.elasticsearch
    - bobbyrenwick.pip
    - nodesource.node
    - kuma
