# Generated by Django 3.2.7 on 2021-11-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watch",
            name="slug",
        ),
        migrations.AddField(
            model_name="watch",
            name="url",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
