# Generated by Django 3.2.7 on 2021-11-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_auto_20211105_1529"),
    ]

    operations = [
        migrations.AddField(
            model_name="watch",
            name="title",
            field=models.CharField(default="", max_length=2048),
            preserve_default=False,
        ),
    ]
