# Generated by Django 3.2.7 on 2021-11-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_read"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompatibilityData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bcd", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
