# Generated by Django 3.2.7 on 2021-12-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_notificationdata_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompatibilityData",
        ),
        migrations.AddField(
            model_name="notification",
            name="starred",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationdata",
            name="type",
            field=models.CharField(
                choices=[("content", "content"), ("compat", "compat")],
                default="compat",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="notificationdata",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
