# Generated by Django 3.2.7 on 2022-01-05 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0006_auto_20220105_0138"),
    ]

    operations = [
        migrations.AddField(
            model_name="watch",
            name="users",
            field=models.ManyToManyField(
                through="notifications.UserWatch", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
