# Generated by Django 3.2.10 on 2022-02-10 09:21

from django.db import migrations


def delete_watchers(apps, schema_editor):
    Watch = apps.get_model("notifications", "Watch")
    Watch.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0010_notification_deleted"),
    ]

    operations = [migrations.RunPython(delete_watchers)]
