# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-26 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=100, verbose_name=b'Banner Name')),
                ('banner_title', models.CharField(max_length=100, verbose_name=b'Banner Title')),
                ('banner_copy', models.TextField(help_text='Main call to action copy has a 200 character limit', max_length=200, verbose_name=b'Main Copy')),
                ('banner_button_copy', models.CharField(max_length=50, verbose_name=b'Button Copy')),
                ('banner_theme', models.CharField(choices=[(b'default', b'Default'), (b'gradient', b'Gradient'), (b'dinohead', b'Dinohead')], default=b'default', max_length=20, verbose_name=b'Theme')),
                ('banner_active', models.BooleanField(verbose_name=b'Activate')),
                ('banner_priority', models.PositiveSmallIntegerField(verbose_name=b'Priority (1-100)')),
            ],
        ),
    ]
