# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-08 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='theme',
            field=models.CharField(choices=[('cta-background-default', 'Default'), ('cta-background-linear', 'Gradient'), ('cta-background-dinohead', 'Dinohead')], default='cta-background-default', max_length=40, verbose_name='Theme'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_url',
            field=models.URLField(default='https://developer.mozilla.org', verbose_name='URL')
        ),
    ]
